<meta charset="UTF-8">
<meta name="google-site-verification" content="jAeZ0ZhZ_HK-yTVS-W2gvUZKafH8g4c27xU9vfDOgek" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="manzowa, Ceci est une plateforme personnel.">
<meta name="keywords" content="manzowa, service api, portofolio, projets, componets">
<!-- <link rel="manifest" href="./manifest.json"> -->
<link href="https://cdn.lineicons.com/5.0/lineicons.css" rel="stylesheet" />
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
<link rel="stylesheet" href="./lib/sgjs/css/sgjs.min.css">
<link rel="shortcut icon" type="image/png" href="./images/logo/logo-48x48.png" />
<link rel="stylesheet" href="./css/manzowa.css">
<script type="module" src="./js/manzowa.js"></script>