version: '3.7'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: school_databases
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge