<!DOCTYPE html>
<html lang="en">
<head>
    <?php include_once App\path('views', 'partials', '_head.phtml'); ?>
    <title>Manzowa </title>
</head>
<body data-spy="scroll" data-target=".navbar" data-offset="40" id="home">

    <!-- Page navigation -->
    <?php include_once App\path('views','layout', '_navigation.phtml');?>
    <!-- End of page navibation -->

    <!-- Page Header -->
    <?php include_once App\path('views', 'layout', '_header.phtml');?>
    <!-- End of Page Header -->
    <main>
        <?php //echo $this['content']; ?>
        <?php include_once App\path('views','home', 'index.phtml');?>
    </main>
    <!-- Page Footer -->
    <?php include_once App\path('views', 'layout', '_footer.phtml');?>
    <!-- End of page footer -->
    <?php include_once App\path("views", "partials", "_foot.phtml"); ?>
</body>
</html>