<section id="portfolio" class="section mo-section-portfolio">
    <div class="mo-container mo-text-center">
        <h6 class="mo-subtitle">Portfolio</h6>
        <h6 class="mo-section-title mb-4">Découvrez mes merveilleuses œuvres</h6>
        <p class="mb-5 pb-4">Exploration de me projets anterieure et en cours de réalisations. <br> Plus plus details allez sur github en haut.</p>

        <div class="mo-row">
            <div class="mo-col">
                <div class="mo-img-wrapper">
                    <img src="./images/folio/folio-1.jpg" alt="">
                    <div class="mo-overlay">
                        <div class="mo-overlay-infos">
                            <h5>Project plugin utilisateur</h5>
                            <a href="javascript:void(0)"><i class="ti-zoom-in"></i></a>
                            <a href="javascript:void(0)"><i class="ti-link"></i></a>
                        </div>
                    </div>
                </div>
                <div class="mo-img-wrapper">
                    <img src="./images/folio/folio-2.jpg" alt="">
                    <div class="mo-overlay">
                        <div class="mo-overlay-infos">
                            <h5>API DOC</h5>
                            <a href="javascript:void(0)"><i class="ti-zoom-in"></i></a>
                            <a href="javascript:void(0)"><i class="ti-link"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="mo-col">
                <div class="mo-img-wrapper">
                    <img src="./images/folio/folio-3.jpg" alt="">
                    <div class="mo-overlay">
                        <div class="mo-overlay-infos">
                            <h5>Project Title</h5>
                            <a href="javascript:void(0)"><i class="ti-zoom-in"></i></a>
                            <a href="javascript:void(0)"><i class="ti-link"></i></a>
                        </div>
                    </div>
                </div>
                <div class="mo-img-wrapper">
                    <img src="./images/folio/folio-4.jpg" alt="">
                    <div class="mo-overlay">
                        <div class="mo-overlay-infos">
                            <h5>Application mobile Wenzischool</h5>
                            <a href="javascript:void(0)"><i class="ti-zoom-in"></i></a>
                            <a href="javascript:void(0)"><i class="ti-link"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="mo-col">
                <div class="mo-img-wrapper">
                    <img src="./images/folio/folio-5.jpg" alt="">
                    <div class="mo-overlay">
                        <div class="mo-overlay-infos">
                            <h5>SITE E-COMMERCE</h5>
                            <a href="javascript:void(0)"><i class="ti-zoom-in"></i></a>
                            <a href="javascript:void(0)"><i class="ti-link"></i></a>
                        </div>
                    </div>
                </div>
                <div class="mo-img-wrapper">
                    <img src="./images/folio/folio-6.jpg" alt="">
                    <div class="mo-overlay">
                        <div class="mo-overlay-infos">
                            <h5>Site Manzowa</h5>
                            <a href="javascript:void(0)"><i class="ti-zoom-in"></i></a>
                            <a href="javascript:void(0)"><i class="ti-link"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>