<section id="projet" class="section mo-section-projet">
    <div class="mo-container mo-text-center">
        <h6 class="mo-subtitle">Projets</h6>
        <h6 class="mo-section-title mb-4">Projet en cours de réalisation</h6>
        <p class="mb-5 pb-4">Ici tout les projets sont en cours de la réalisation et d'autres sont en mis à jours.<br>Cliquez sur le button voir pour visualiser en détail.</p>
        <div class="mo-row mo-text-left">
            <div class="mo-col">
                <div class="mo-card border mb-4">
                    <img src="./images/projet/projet-1.jpg" alt="" class="mo-card-img-top w-100">
                    <div class="mo-card-body">
                        <h5 class="mo-card-title">Projet Mobile</h5>
                        <div class="post-details">
                            <a href="javascript:void(0)">Wenzischool</a>
                        </div>
                        <p>Wenzischool est une application mobile qui permet de s'informer sur les écoles et les événements lien aux écoles.</p>
                        <button class="mo-btn-voir mo-btn mo-rounded mo-not-allowed">voir</button>
                    </div>
                </div>
            </div>
            <div class="mo-col">
                <div class="mo-card border mb-4">
                    <img src="./images/projet/projet-2.jpg" alt="" class="mo-card-img-top w-100">
                    <div class="mo-card-body">
                        <h5 class="mo-card-title">Projet Web</h5>
                        <div class="post-details">
                            <a href="javascript:void(0)">Aapi school</a>
                        </div>
                        <p>API school est une plateforme qui fournie l'API destiné à l'application mobile Wenzischool.</p><br/>
                        <button class="mo-btn-voir mo-btn mo-rounded mo-not-allowed">voir</button>
                    </div>
                </div>
            </div>
            <div class="mo-col">
                <div class="mo-card border mb-4">
                    <img src="./images/projet/projet-3.jpg" alt="" class="mo-card-img-top w-100">
                    <div class="mo-card-body">
                        <h5 class="mo-card-title">Projet Web</h5>
                        <div class="post-details">
                            <a href="javascript:void(0)">Validator FORM</a>
                        </div>
                        <p>Validator fom est un composant PHP qui permet de valider l'intégrite de données soumis via un formulaire.<br/><br/></p>
                        <button class="mo-btn-voir mo-btn mo-rounded mo-not-allowed">voir</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>