<section id="service" class="section mo-section-service">
    <div class="mo-container mo-text-center mt-4">
        <h6 class="mo-subtitle">Service</h6>
        <h6 class="mo-section-title mb-4">Ce que je fais</h6>
        <p class="mb-5 pb-4">Voici mes domaines d'expertises dans IT. <br> rerum commodi corrupti, temporibus non quam.</p>

        <div class="mo-row">
            <div class="mo-item">
                <div class="mo-custom-card mo-card border">
                    <div class="mo-card-body">
                        <i class="lni lni-code-1"></i>
                        <h5 class="mo-subtitle mo-textColor-light">Developpeur Back </h5>
                    </div>
                </div>
            </div>
            <div class="mo-item">
                <div class="mo-custom-card mo-card border">
                    <div class="mo-card-body">
                        <i class="lni lni-code-1"></i>
                        <h5 class="mo-subtitle mo-textColor-light">Développeur Front </h5>
                    </div>
                </div>
            </div>
            <div class="mo-item">
                <div class="mo-custom-card mo-card border">
                    <div class="mo-card-body">
                        <i class="lni lni-phone"></i>
                        <h5 class="mo-subtitle mo-textColor-light">Développeur Mobile</h5>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>