<?php //$this->extend('base') ?>
<!-- Service section -->
<?php include_once App\path('views', 'home', 'section', '_service.phtml');?>
<!-- End of Sectoin -->

<!-- Skills section -->
<?php include_once App\path('views','home', 'section', '_skill.phtml');?>
<!-- End of Skills sections -->

<!-- Portfolio section -->
<?php include_once App\path('views','home', 'section', '_portfolio.phtml');?>
<!-- End of portfolio section -->
<!-- Projets Section -->
<?php include_once App\path('views','home', 'section', '_projet.phtml');?>