// config/permissions.js
export const PERMISSIONS = {
  CREATE_USER: 1,
  EDIT_USER: 2,
  DELETE_USER: 3,
  VIEW_USER: 4,

  CREATE_SCHOOL: 5,
  EDIT_SCHOOL: 6,
  DELETE_SCHOOL: 7,
  VIEW_SCHOOL: 8,

  CREATE_EVENT: 9,
  EDIT_EVENT: 10,
  DELETE_EVENT: 11,
  VIEW_EVENT: 12,

  CREATE_COMMENT: 13,
  EDIT_COMMENT: 14,
  DELETE_COMMENT: 15,
  VIEW_COMMENT: 16,

  CREATE_RATING: 17,
  EDIT_RATING: 18,
  DELETE_RATING: 19,
  VIEW_RATING: 20,

  CREATE_IMAGE: 21,
  EDIT_IMAGE: 22,
  DELETE_IMAGE: 23,
  VIEW_IMAGE: 24,
};
