<footer class="page-footer mo-layout-footer">
    <div class="mo-container">
        <div class="mo-content">
            <div class="mo-row">
                <div class="">
                    <p>Copyright <script>
                            document.write(new Date().getFullYear())
                        </script> &copy; <a href="http://manzowa.com" target="_blank">manzowa</a></p>
                </div>
                <div class="">
                    <div class="mo-socials">
                        <a class="mo-social-item" href="https://www.facebook.com/profile.php?id=61570562905345&is_tour_completed" target="_blank"><i class="lni lni-facebook"></i></a>
                        <a class="mo-social-item" href="https://github.com/manzowa" target="_blank"><i class="lni lni-github"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>