<header class="mo-layout-header" id="home">
    <div class="mo-container">
        <div class="mo-layout-header-content">
            <div class="mo-infos">
                <h6 class="mo-subtitle">Salut, Je suis</h6>
                <h6 class="mo-title">Christian SHUNGU</h6>
                <p>Developpeur FULLSTACK</p>
                <div class="buttons pt-3">
                    <button class="mo-btn mo-btn-warning mo-rounded">ENGAGEZ-MOI</button>
                    <a href="./docs/cv-shungu.pdf" download>
                        <button class="mo-btn mo-btn-primary mo-rounded mo-shadow">TÉLÉCHARGER LE CV</button>
                    </a>
                </div>
                <div class="mo-socials mt-4">
                    <a class="mo-social-item" href="https://www.facebook.com/profile.php?id=61570562905345&is_tour_completed" target="_blank"><i class="lni lni-facebook"></i></a>
                    <a class="mo-social-item" href="https://github.com/manzowa" target="_blank"><i class="lni lni-github"></i></a>
                </div>
            </div>
        </div>
        
    </div>
    <!-- Header-widget -->
    <div class="mo-widget">
        <div class="mo-widget-item">
            <h2>4</h2>
            <p>Clients satisfaits</p>
        </div>
        <div class="mo-widget-item">
            <h2>5</h2>
            <p>Projet terminé</p>
        </div>
        <div class="mo-widget-item">
            <h2>1</h2>
            <p>Récompenses remportées</p>
        </div>
    </div>
</header>